# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  k8s:
    image: twallace27603/k8swebapp:1.0
    depends_on: 
      - mongo
      - db
    ports:
      - 80:80
    environment:
      - 'SQLConnection=Server=db;Database=Trivia;Uid=sa;Pwd=B@dpa55w0rd;'
      - MongoServer=mongo
      - Debug=no

  mongo:
    image: twallace27603/k8smongo:1.0
  db:
    image: twallace27603/k8ssql:1.0
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=B@dpa$$w0rd
      - MSSQL_PID=Express
