apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: twallace27603/k8swebapp:1.0
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1"
        ports:
        - containerPort: 80
        env:
          - name: SQLConnection
            value: "Server=localhost;Database=Trivia;Uid=sa;Pwd=B@dpa55w0rd;"
          - name: MongoServer
            value: "localhost"
          - name: Debug 
            value: "yes"
      - name: db
        image: twallace27603/k8ssql:1.0
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1"
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: "B@dpa55w0rd"
          - name: MSSQL_PID
            value: "Express"
      - name: mongo
        image: twallace27603/k8smongo:1.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
---        
apiVersion: v1
kind: Service
metadata:
  name: quizservice
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 80
  
